## **``GroupedKFold``**
##### **It is the version of KFold which makes sure that same group(i.e. more than one group can be present in the test set) is not present in both training ans testing sets.**

In [10]:
import numpy as np
import pandas as pd

In [11]:
from sklearn.model_selection import GroupKFold

In [12]:
gkf = GroupKFold(n_splits=3)

In [13]:
df = pd.DataFrame({'col1':['Sachin','Rahul','Saurav','Virat','Dhoni','Hayden','Zaheer','Sreeshanth','Bumrah','Kumble'],
                   'col2':['Steve','Ricky','Lara','Klusner','Warne','Donald','Mcgrath','Kasprowiz','Pollock','Steyn'],
              'Label':['Opener','Opener','Opener','Non-Opener','Non-Opener','Non-Opener','Non-Opener','Non-Opener','Non-Opener','Non-Opener'],
                   'Group':['All rounder','Batsmen','Batsmen','All rounder','All rounder','All rounder','Bowler','Bowler','Bowler','Bowler']})

In [14]:
df

col1       col2       Label        Group
0      Sachin      Steve      Opener  All rounder
1       Rahul      Ricky      Opener      Batsmen
2      Saurav       Lara      Opener      Batsmen
3       Virat    Klusner  Non-Opener  All rounder
4       Dhoni      Warne  Non-Opener  All rounder
5      Hayden     Donald  Non-Opener  All rounder
6      Zaheer    Mcgrath  Non-Opener       Bowler
7  Sreeshanth  Kasprowiz  Non-Opener       Bowler
8      Bumrah    Pollock  Non-Opener       Bowler
9      Kumble      Steyn  Non-Opener       Bowler

In [17]:
X=df[['col1','col2']]
y=df['Label']

In [35]:
for train , test in gkf.split(X=df[['col1','col2']],y=df['Label'],groups=df['Group']):
    print(train)
    print(test)

[0 1 2 3 4 5]
[6 7 8 9]
[1 2 6 7 8 9]
[0 3 4 5]
[0 3 4 5 6 7 8 9]
[1 2]


In [19]:
for train , test in gkf.split(X=df[['col1','col2']],y=df['Label'],groups=df['Group']):
    X_train , X_test = X.iloc[train] , X.iloc[test]
    y_train, y_test = y.iloc[train] , y.iloc[test]

In [20]:
X_train

col1       col2
0      Sachin      Steve
3       Virat    Klusner
4       Dhoni      Warne
5      Hayden     Donald
6      Zaheer    Mcgrath
7  Sreeshanth  Kasprowiz
8      Bumrah    Pollock
9      Kumble      Steyn

In [21]:
X_test

col1   col2
1   Rahul  Ricky
2  Saurav   Lara

In [22]:
y_train

0        Opener
3    Non-Opener
4    Non-Opener
5    Non-Opener
6    Non-Opener
7    Non-Opener
8    Non-Opener
9    Non-Opener
Name: Label, dtype: object

In [23]:
y_test

1    Opener
2    Opener
Name: Label, dtype: object

## **``LeaveOneGroupOut``**
##### **It make sures that one group is not present in the training set.**

In [24]:
from sklearn.model_selection import LeaveOneGroupOut

In [25]:
logo = LeaveOneGroupOut()

In [26]:
df

col1       col2       Label        Group
0      Sachin      Steve      Opener  All rounder
1       Rahul      Ricky      Opener      Batsmen
2      Saurav       Lara      Opener      Batsmen
3       Virat    Klusner  Non-Opener  All rounder
4       Dhoni      Warne  Non-Opener  All rounder
5      Hayden     Donald  Non-Opener  All rounder
6      Zaheer    Mcgrath  Non-Opener       Bowler
7  Sreeshanth  Kasprowiz  Non-Opener       Bowler
8      Bumrah    Pollock  Non-Opener       Bowler
9      Kumble      Steyn  Non-Opener       Bowler

In [34]:
for train , test in logo.split(X=df[['col1','col2']],y=df['Label'],groups=df['Group']):
    print(train)
    print(test)

[1 2 6 7 8 9]
[0 3 4 5]
[0 3 4 5 6 7 8 9]
[1 2]
[0 1 2 3 4 5]
[6 7 8 9]


In [29]:
for train , test in logo.split(X=df[['col1','col2']],y=df['Label'],groups=df['Group']):
    X_train , X_test = X.iloc[train] , X.iloc[test]
    y_train , y_test = y.iloc[train] , y.iloc[test]

In [30]:
X_train

col1     col2
0  Sachin    Steve
1   Rahul    Ricky
2  Saurav     Lara
3   Virat  Klusner
4   Dhoni    Warne
5  Hayden   Donald

In [31]:
X_test

col1       col2
6      Zaheer    Mcgrath
7  Sreeshanth  Kasprowiz
8      Bumrah    Pollock
9      Kumble      Steyn

In [32]:
y_train

0        Opener
1        Opener
2        Opener
3    Non-Opener
4    Non-Opener
5    Non-Opener
Name: Label, dtype: object

In [33]:
y_test

6    Non-Opener
7    Non-Opener
8    Non-Opener
9    Non-Opener
Name: Label, dtype: object

In [36]:
df

col1       col2       Label        Group
0      Sachin      Steve      Opener  All rounder
1       Rahul      Ricky      Opener      Batsmen
2      Saurav       Lara      Opener      Batsmen
3       Virat    Klusner  Non-Opener  All rounder
4       Dhoni      Warne  Non-Opener  All rounder
5      Hayden     Donald  Non-Opener  All rounder
6      Zaheer    Mcgrath  Non-Opener       Bowler
7  Sreeshanth  Kasprowiz  Non-Opener       Bowler
8      Bumrah    Pollock  Non-Opener       Bowler
9      Kumble      Steyn  Non-Opener       Bowler

#### **Difference b/w GroupKFold and LeaveOneGroupOut**

In [37]:
logo_grp = [0,0,1,1,2,2,2,3,3,3]

In [41]:
df['new_logo'] = logo_grp

In [42]:
df

col1       col2       Label        Group  new_logo
0      Sachin      Steve      Opener  All rounder         0
1       Rahul      Ricky      Opener      Batsmen         0
2      Saurav       Lara      Opener      Batsmen         1
3       Virat    Klusner  Non-Opener  All rounder         1
4       Dhoni      Warne  Non-Opener  All rounder         2
5      Hayden     Donald  Non-Opener  All rounder         2
6      Zaheer    Mcgrath  Non-Opener       Bowler         2
7  Sreeshanth  Kasprowiz  Non-Opener       Bowler         3
8      Bumrah    Pollock  Non-Opener       Bowler         3
9      Kumble      Steyn  Non-Opener       Bowler         3

In [43]:
for train , test in gkf.split(X=df[['col1','col2']],y=df['Label'],groups=logo_grp):
    print(train)
    print(test)

[0 1 2 3 4 5 6]
[7 8 9]
[0 1 2 3 7 8 9]
[4 5 6]
[4 5 6 7 8 9]
[0 1 2 3]


In [40]:
for train , test in logo.split(X=df[['col1','col2']],y=df['Label'],groups=logo_grp):
    print(train)
    print(test)

[2 3 4 5 6 7 8 9]
[0 1]
[0 1 4 5 6 7 8 9]
[2 3]
[0 1 2 3 7 8 9]
[4 5 6]
[0 1 2 3 4 5 6]
[7 8 9]


## **``LeavePGroupOut``**
##### **It make sures that p number of groups are not present in the training set.**

In [44]:
from sklearn.model_selection import LeavePGroupsOut

In [56]:
lpgo = LeavePGroupsOut(n_groups=2)

In [57]:
df

col1       col2       Label        Group  new_logo
0      Sachin      Steve      Opener  All rounder         0
1       Rahul      Ricky      Opener      Batsmen         0
2      Saurav       Lara      Opener      Batsmen         1
3       Virat    Klusner  Non-Opener  All rounder         1
4       Dhoni      Warne  Non-Opener  All rounder         2
5      Hayden     Donald  Non-Opener  All rounder         2
6      Zaheer    Mcgrath  Non-Opener       Bowler         2
7  Sreeshanth  Kasprowiz  Non-Opener       Bowler         3
8      Bumrah    Pollock  Non-Opener       Bowler         3
9      Kumble      Steyn  Non-Opener       Bowler         3

In [58]:
for train , test in lpgo.split(X=df[['col1','col2']],y=df['Label'],groups=logo_grp):
    print(train)
    print(test)
    print('####')

[4 5 6 7 8 9]
[0 1 2 3]
####
[2 3 7 8 9]
[0 1 4 5 6]
####
[2 3 4 5 6]
[0 1 7 8 9]
####
[0 1 7 8 9]
[2 3 4 5 6]
####
[0 1 4 5 6]
[2 3 7 8 9]
####
[0 1 2 3]
[4 5 6 7 8 9]
####


In [53]:
lpgo = LeavePGroupsOut(n_groups=3)

In [52]:
df

col1       col2       Label        Group  new_logo
0      Sachin      Steve      Opener  All rounder         0
1       Rahul      Ricky      Opener      Batsmen         0
2      Saurav       Lara      Opener      Batsmen         1
3       Virat    Klusner  Non-Opener  All rounder         1
4       Dhoni      Warne  Non-Opener  All rounder         2
5      Hayden     Donald  Non-Opener  All rounder         2
6      Zaheer    Mcgrath  Non-Opener       Bowler         2
7  Sreeshanth  Kasprowiz  Non-Opener       Bowler         3
8      Bumrah    Pollock  Non-Opener       Bowler         3
9      Kumble      Steyn  Non-Opener       Bowler         3

In [54]:
for train , test in lpgo.split(X=df[['col1','col2']],y=df['Label'],groups=logo_grp):
    print(train)
    print(test)
    print('####')

[7 8 9]
[0 1 2 3 4 5 6]
####
[4 5 6]
[0 1 2 3 7 8 9]
####
[2 3]
[0 1 4 5 6 7 8 9]
####
[0 1]
[2 3 4 5 6 7 8 9]
####


## **``Group Shuffle Split``**
##### **It runs as a combination of ShuffleSplit and LeavePGroupsOut and generates the randomized sequences of sets.**

In [59]:
from sklearn.model_selection import GroupShuffleSplit

In [60]:
gss = GroupShuffleSplit(n_splits=3,test_size=0.40,train_size=0.60)

In [61]:
for train , test in gss.split(X=df[['col1','col2']],y=df['Label'],groups=logo_grp):
    print(train)
    print(test)
    print('####')

[0 1 7 8 9]
[2 3 4 5 6]
####
[0 1 7 8 9]
[2 3 4 5 6]
####
[0 1 4 5 6]
[2 3 7 8 9]
####


In [70]:
gss = GroupShuffleSplit(n_splits=7,test_size=0.40)

In [71]:
for train , test in gss.split(X=df[['col1','col2']],y=df['Label'],groups=logo_grp):
    print(train)
    print(test)
    print('####')

[4 5 6 7 8 9]
[0 1 2 3]
####
[4 5 6 7 8 9]
[0 1 2 3]
####
[4 5 6 7 8 9]
[0 1 2 3]
####
[0 1 2 3]
[4 5 6 7 8 9]
####
[0 1 4 5 6]
[2 3 7 8 9]
####
[2 3 4 5 6]
[0 1 7 8 9]
####
[0 1 4 5 6]
[2 3 7 8 9]
####


## **``Predefined Split``**
##### **It is a user defined split where user can defined the pattern of split in 0(test_fold) and -1(train_fold) form.**

In [72]:
from sklearn.model_selection import PredefinedSplit

In [73]:
df

col1       col2       Label        Group  new_logo
0      Sachin      Steve      Opener  All rounder         0
1       Rahul      Ricky      Opener      Batsmen         0
2      Saurav       Lara      Opener      Batsmen         1
3       Virat    Klusner  Non-Opener  All rounder         1
4       Dhoni      Warne  Non-Opener  All rounder         2
5      Hayden     Donald  Non-Opener  All rounder         2
6      Zaheer    Mcgrath  Non-Opener       Bowler         2
7  Sreeshanth  Kasprowiz  Non-Opener       Bowler         3
8      Bumrah    Pollock  Non-Opener       Bowler         3
9      Kumble      Steyn  Non-Opener       Bowler         3

#### **Case:I**

In [75]:
test_folds = [0,-1,0,-1,0,-1,0,-1,0,-1]

In [76]:
pds = PredefinedSplit(test_fold=test_folds)

In [77]:
for train , test in pds.split(X=df):
    print(train)
    print(test)

[1 3 5 7 9]
[0 2 4 6 8]


#### **Case:II**

In [78]:
test_folds = [0,0,0,0,0,0,-1,-1,-1,0]

In [79]:
pds = PredefinedSplit(test_fold=test_folds)

In [80]:
for train , test in pds.split(X=df):
    print(train)
    print(test)

[6 7 8]
[0 1 2 3 4 5 9]
