## **``Stratified KFold``**
##### **It returns the indices of the data points for the training and testing datasets having equal percentages of data from all the target classes.**

In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.model_selection import StratifiedKFold

In [8]:
stkf = StratifiedKFold(n_splits=2,shuffle=True)

In [9]:
df = pd.DataFrame({'col1':['Sachin','Rahul','Saurav','Virat','Dhoni'],
             'col2':['Steve','Ricky','Lara','Klusner','Warne'],
              'Label':['Opener','Opener','Opener','Non-Opener','Non-Opener']})

In [10]:
df

col1     col2       Label
0  Sachin    Steve      Opener
1   Rahul    Ricky      Opener
2  Saurav     Lara      Opener
3   Virat  Klusner  Non-Opener
4   Dhoni    Warne  Non-Opener

In [18]:
for train ,test in stkf.split(X=df[['col1','col2']],y=df['Label']):
    print(train)
    print(test)
    print('$$$$')

[1 4]
[0 2 3]
$$$$
[0 2 3]
[1 4]
$$$$


#### **CASE : II**

In [22]:
X, y = np.ones((30, 1)), np.hstack(([0] * 25, [1] * 5))

In [23]:
X

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [24]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1])

In [26]:
np.bincount(y)

array([25,  5], dtype=int64)

In [27]:
stkf = StratifiedKFold(n_splits=3,shuffle=False)

In [30]:
for train, test in stkf.split(X=X,y=y):
    print(np.bincount(y[train]))
    print(np.bincount(y[test]))
    print('$$$')

[16  4]
[9 1]
$$$
[17  3]
[8 2]
$$$
[17  3]
[8 2]
$$$


#### **CASE : III :: Difference with KFold**

In [31]:
from sklearn.model_selection import KFold

In [32]:
kf = KFold(n_splits=3)

In [33]:
for train , test in kf.split(X=X,y=y):
    print(np.bincount(y[train]))
    print(np.bincount(y[test]))
    print('$$$')

[15  5]
[10]
$$$
[15  5]
[10]
$$$
[20]
[5 5]
$$$


#### **CASE : IV :: Applying Stratified KFold on Real Data**

In [105]:
liver_data = pd.read_csv("../Datasets/indian_liver_patient.csv")
liver_data.head()

Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0   65  Female              0.7               0.1                   187   
1   62    Male             10.9               5.5                   699   
2   62    Male              7.3               4.1                   490   
3   58    Male              1.0               0.4                   182   
4   72    Male              3.9               2.0                   195   

   Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                        16                          18             6.8   
1                        64                         100             7.5   
2                        60                          68             7.0   
3                        14                          20             6.8   
4                        27                          59             7.3   

   Albumin  Albumin_and_Globulin_Ratio  Dataset  
0      3.3                        0.90        1  
1      3.2                        0.74        1  
2      3.3                        0.89        1  
3      3.4                        1.00        1  
4      2.4                        0.40        1

In [106]:
np.bincount(liver_data['Dataset'])

array([  0, 416, 167], dtype=int64)

In [107]:
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import LabelEncoder as LE

In [108]:
stkf = StratifiedKFold(n_splits=2)

In [109]:
le = LE()

In [110]:
liver_data['Gender'] = le.fit_transform(liver_data['Gender'])

In [111]:
liver_data['Albumin_and_Globulin_Ratio'].fillna(method='bfill',inplace=True)

In [112]:
from sklearn.model_selection import train_test_split

In [113]:
liver_data.head()

Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0   65       0              0.7               0.1                   187   
1   62       1             10.9               5.5                   699   
2   62       1              7.3               4.1                   490   
3   58       1              1.0               0.4                   182   
4   72       1              3.9               2.0                   195   

   Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                        16                          18             6.8   
1                        64                         100             7.5   
2                        60                          68             7.0   
3                        14                          20             6.8   
4                        27                          59             7.3   

   Albumin  Albumin_and_Globulin_Ratio  Dataset  
0      3.3                        0.90        1  
1      3.2                        0.74        1  
2      3.3                        0.89        1  
3      3.4                        1.00        1  
4      2.4                        0.40        1

In [114]:
X1 = liver_data.iloc[:,0:-1]

In [115]:
X1.head()

Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0   65       0              0.7               0.1                   187   
1   62       1             10.9               5.5                   699   
2   62       1              7.3               4.1                   490   
3   58       1              1.0               0.4                   182   
4   72       1              3.9               2.0                   195   

   Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                        16                          18             6.8   
1                        64                         100             7.5   
2                        60                          68             7.0   
3                        14                          20             6.8   
4                        27                          59             7.3   

   Albumin  Albumin_and_Globulin_Ratio  
0      3.3                        0.90  
1      3.2                        0.74  
2      3.3                        0.89  
3      3.4                        1.00  
4      2.4                        0.40

In [116]:
y1 = liver_data.iloc[:,-1]

In [117]:
y1.head()

0    1
1    1
2    1
3    1
4    1
Name: Dataset, dtype: int64

In [128]:
X_train, X_test, y_train, y_test = train_test_split(X1, y1,test_size=0.25)

In [119]:
np.bincount(y_train)

array([  0, 312, 125], dtype=int64)

In [120]:
np.bincount(y_test)

array([  0, 104,  42], dtype=int64)

In [83]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

In [84]:
rfc = RandomForestClassifier(n_estimators=35)

In [91]:
from sklearn.model_selection import RepeatedStratifiedKFold

#### **Repeated StratifiedKFold**
##### **It repeats the Stratified KFold Cross Validator.**

In [95]:
cross_val_score(rfc,X_train,y_train,cv=RepeatedStratifiedKFold(n_splits=10,n_repeats=2)) 

array([0.68181818, 0.70454545, 0.72727273, 0.68181818, 0.72727273,
       0.61363636, 0.68181818, 0.76744186, 0.65116279, 0.81395349,
       0.59090909, 0.65909091, 0.70454545, 0.77272727, 0.70454545,
       0.81818182, 0.77272727, 0.69767442, 0.72093023, 0.69767442])

In [49]:
for train, test in stkf.split(X=X_train,y=y_train):
    print(train)
    print(test)
    print('###')

[206 207 211 216 217 221 224 226 227 228 229 230 231 232 233 234 235 236
 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253 254
 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271 272
 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288 289 290
 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305 306 307 308
 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324 325 326
 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341 342 343 344
 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359 360 361 362
 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377 378 379 380
 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395 396 397 398
 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415 416
 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431 432 433 434
 435 436]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27 

## **``Stratified ShuffleSplit``**
##### **It is the mixture of StratifiedKFold and Shufflesplit which returns the stratified samples of randomized folds.**

In [125]:
from sklearn.model_selection import StratifiedShuffleSplit

In [126]:
sss = StratifiedShuffleSplit(n_splits = 2)

In [139]:
for train_idx , test_idx in sss.split(X_train,y_train):
    X_new_train, X_new_test = X_train.iloc[train_idx], X_train.iloc[test_idx]
    y_new_train , y_new_test = y_train.iloc[train_idx], y_train.iloc[test_idx]

In [141]:
X_new_train.head()

Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
58    51       1              0.8               0.2                   367   
192   60       1              2.3               0.6                   272   
434   30       0              0.7               0.2                   194   
544   54       0              5.5               3.2                   350   
443   42       0              0.7               0.2                   152   

     Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
58                         42                          18             5.2   
192                        79                          51             6.6   
434                        32                          36             7.5   
544                        67                          42             7.0   
443                        35                          81             6.2   

     Albumin  Albumin_and_Globulin_Ratio  
58       2.0                        0.60  
192      3.5                        1.10  
434      3.6                        0.92  
544      3.2                        0.80  
443      3.2                        1.06

In [142]:
X_new_test.head()

Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
385   50       1              0.8               0.2                   152   
17    33       1              1.6               0.5                   165   
286   34       0              0.8               0.2                   192   
379   72       1              0.7               0.2                   185   
118   32       1             15.9               7.0                   280   

     Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
385                        29                          30             7.4   
17                         15                          23             7.3   
286                        15                          12             8.6   
379                        16                          22             7.3   
118                      1350                        1600             5.6   

     Albumin  Albumin_and_Globulin_Ratio  
385      4.1                        1.30  
17       3.5                        0.92  
286      4.7                        1.20  
379      3.7                        1.00  
118      2.8                        1.00

In [143]:
np.bincount(y_new_train)

array([  0, 281, 112], dtype=int64)

In [144]:
np.bincount(y_new_test)

array([ 0, 32, 12], dtype=int64)

In [145]:
cross_val_score(rfc,X_train,y_train,cv=StratifiedShuffleSplit(n_splits=10))

array([0.68181818, 0.72727273, 0.65909091, 0.75      , 0.68181818,
       0.65909091, 0.79545455, 0.72727273, 0.77272727, 0.75      ])

In [146]:
from sklearn.model_selection import learning_curve , validation_curve

In [148]:
l_results = learning_curve(rfc,X_train,y_train,cv=StratifiedShuffleSplit(n_splits=10))

In [155]:
for a in l_results:
    print(a)

[ 39 127 216 304 393]
[[1.         1.         1.         1.         1.         1.
  1.         1.         1.         0.97435897]
 [1.         1.         1.         1.         1.         1.
  1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.         0.99537037
  1.         1.         1.         1.        ]
 [0.99671053 0.99671053 1.         1.         1.         1.
  1.         0.99671053 0.99671053 1.        ]
 [0.99745547 1.         1.         1.         1.         1.
  1.         1.         1.         1.        ]]
[[0.75       0.63636364 0.72727273 0.54545455 0.79545455 0.75
  0.72727273 0.65909091 0.79545455 0.72727273]
 [0.68181818 0.59090909 0.68181818 0.72727273 0.75       0.75
  0.70454545 0.70454545 0.75       0.79545455]
 [0.72727273 0.65909091 0.68181818 0.75       0.72727273 0.68181818
  0.75       0.65909091 0.75       0.68181818]
 [0.72727273 0.65909091 0.68181818 0.75       0.65909091 0.70454545
  0.75       0.68181818 0.7727272